# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "MAYO1.1" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt-get install -y make
        sudo apt-get install -y sagemath
        sage --pip install pycryptodomex
    - name: Check installed versions
      run: |
        # Print Python version
        python --version
        # Print pip version
        pip --version
        # Print installed pycryptodomex version
        python -c "import Cryptodome; print('pycryptodomex version:', Cryptodome.__version__)"
        # Print SageMath version
        sage --version
    - name: Test application
      run: |
        make test
